name: helm-cli
author: meysam@licenseware.io
branding:
  color: green
  icon: package
description: Deploy Helm chart in a GitHub action
inputs:
  action:
    default: upgrade -i
    description: upgrade -i, upgrade, install, uninstall, etc.
    required: false
  atomic:
    default: "1"
    description: Whether or not to pass `--atomic` to Helm
    required: false
  build-dependencies:
    default: "0"
    description: Whether or not to run `helm dependency build` before deployment
    required: false
  chart-dir:
    default: helm
    description: Relative path from the repository root directory
    required: false
  chmod-kubeconfig:
    default: "1"
    description: Whether or not to change the access for the kubeconfig file to 600
    required: false
  cleanup:
    default: "1"
    description: Whether or not to delete all the kubeconfig & values files after deployment
    required: false
  create-namespace:
    default: "0"
    description: Whether or not to pass `--create-namespace` to Helm
    required: false
  helm-version:
    default: v3.10.1
    required: false
  kubeconfig:
    description: 'A JSON/YAML encoded string e.g. {"key": "value"}. Mutually exclusive with `kubeconfig-filepath`'
    required: false
  kubeconfig-filepath:
    description: Path to kubeconfig file. Mutually exclusive with `kubeconfig`
    required: false
  namespace:
    default: default
    required: false
  release-name:
    default: ${{ github.event.repository.name }}
    required: false
  update-dependencies:
    default: "1"
    description: Whether or not to run `helm dependency update` before deployment
    required: false
  values:
    default: ""
    description: A comma separated list of values e.g. "key1=value1,key2=value2"
    required: false
  values-file:
    default: ""
    description: 'A JSON/YAML encoded string e.g. {"key": "value"}'
    required: false
  values-filepath:
    default: ""
    description: A relative/absolute path to a file containing the YAML/JSON values
    required: false
  wait:
    default: "1"
    description: Whether or not to pass `--wait` to Helm
    required: false
runs:
  using: composite
  steps:
    - if: inputs.kubeconfig == '' && inputs.kubeconfig-filepath == ''
      name: Error - no kubeconfig provided
      run: |
        echo "Error: You must provide either `kubeconfig` or `kubeconfig-filepath`"
        exit 1
      shell: bash
    - if: inputs.kubeconfig != '' && inputs.kubeconfig-filepath != ''
      name: Error - both kubeconfig and kubeconfig-filepath provided
      run: |
        echo "Error: You must provide either `kubeconfig` or `kubeconfig-filepath` but not both"
        exit 1
      shell: bash
    - env:
        DESIRED_VERSION: ${{ inputs.helm-version }}
      name: Install Helm ${{ inputs.helm-version }}
      run: curl -fsSL https://git.io/get_helm.sh | bash
      shell: bash
    - if: inputs.update-dependencies == '1'
      name: Update Helm dependencies
      run: helm dep update ${{ inputs.chart-dir }}
      shell: bash
    - if: inputs.build-dependencies == '1'
      name: Build Helm dependencies
      run: helm dep build ${{ inputs.chart-dir }}
      shell: bash
    - id: generate-random-filepath
      if: inputs.kubeconfig != '' || inputs.values-file != ''
      name: Generate kubeconfig & values random filepath
      run: |
        echo "::set-output name=KUBECONFIG_FILEPATH::${{ github.run_id }}-${{ github.run_attempt }}-${RANDOM}-kubeconfig"
        echo "::set-output name=VALUES_FILEPATH::${{ github.run_id }}-${{ github.run_attempt }}-${RANDOM}-values"
      shell: bash
    - if: inputs.values-file != ''
      name: Prepare values file
      run: |
        cat << 'EOF' > ${{ steps.generate-random-filepath.outputs.VALUES_FILEPATH }}
        ${{ inputs.values-file }}
        EOF
        chmod 600 ${{ steps.generate-random-filepath.outputs.VALUES_FILEPATH }}
      shell: bash
    - if: inputs.kubeconfig != ''
      name: Prepare KUBECONFIG
      run: |
        cat << 'EOF' > ${{ steps.generate-random-filepath.outputs.KUBECONFIG_FILEPATH }}
        ${{ inputs.kubeconfig }}
        EOF
        chmod 600 ${{ steps.generate-random-filepath.outputs.KUBECONFIG_FILEPATH }}
      shell: bash
    - if: inputs.chmod-kubeconfig == '1'
      name: Change access for KUBECONFIG
      run: |
        [[ -f ${{ inputs.kubeconfig-filepath }} ]] && chmod 600 ${{ inputs.kubeconfig-filepath }}
      shell: bash
    - name: Deploy with Helm
      run: |
        helm ${{ inputs.action }} ${{ inputs.release-name }} ${{ inputs.chart-dir }} \
          --kubeconfig ${{ inputs.kubeconfig-filepath || steps.generate-random-filepath.outputs.KUBECONFIG_FILEPATH }} \
          --namespace ${{ inputs.namespace }} \
          $([[ "${{ inputs.create-namespace }}" == "1" ]] && echo '--create-namespace') \
          $([[ "${{ inputs.atomic }}" == "1" ]] && echo '--atomic') \
          $([[ "${{ inputs.wait }}" == "1" ]] && echo '--wait') \
          $([[ "${{ inputs.values-file }}" != "" ]] && echo "--values ${{ github.run_id }}") \
          $([[ "${{ inputs.values-filepath }}" != "" ]] && echo "--values ${{ inputs.values-filepath }}") \
          $([[ "${{ inputs.values }}" != "" ]] && echo "--set ${{ inputs.values }}")
      shell: bash
    - if: always() && inputs.cleanup == '1'
      name: Cleanup
      run: |
        rm -f ${{ steps.generate-random-filepath.outputs.KUBECONFIG_FILEPATH }} \
          ${{ steps.generate-random-filepath.outputs.VALUES_FILEPATH }} \
          ${{ inputs.values-filepath }} \
          ${{ inputs.kubeconfig-filepath }}
        echo "Cleanup complete"
      shell: bash
