name: helm-cli
author: meysam@licenseware.io
branding:
  color: green
  icon: package
description: Deploy Helm chart in a GitHub action
inputs:
  action:
    default: upgrade -i
    description: upgrade -i, upgrade, install, uninstall, etc.
    required: false
  atomic:
    default: "1"
    description: Whether or not to pass `--atomic` to Helm
    required: false
  build-dependencies:
    default: "1"
    description: Whether or not to run `helm dependency build` before deployment
    required: false
  chart-dir:
    default: helm
    description: Relative path from the repository root directory
    required: false
  create-namespace:
    default: "0"
    description: Whether or not to pass `--create-namespace` to Helm
    required: false
  helm-version:
    default: v3.9.4
    required: false
  kubeconfig:
    description: 'A JSON/YAML encoded string e.g. {"key": "value"}. Mutually exclusive with `kubeconfig-file`'
    required: false
  kubeconfig-file:
    description: Path to kubeconfig file. Mutually exclusive with `kubeconfig`
    required: false
  namespace:
    default: default
    required: false
  release-name:
    default: ${{ github.event.repository.name }}
    required: false
  update-dependencies:
    default: "0"
    description: Whether or not to run `helm dependency update` before deployment
    required: false
  values:
    default: ""
    description: A comma separated list of values e.g. "key1=value1,key2=value2"
    required: false
  values-file:
    default: ""
    description: 'A JSON/YAML encoded string e.g. {"key": "value"}'
    required: false
  values-filepath:
    default: ""
    description: A relative/absolute path to a file containing the YAML/JSON values
    required: false
  wait:
    default: "1"
    description: Whether or not to pass `--wait` to Helm
    required: false
runs:
  using: composite
  steps:
    - if: inputs.kubeconfig == '' && inputs.kubeconfig-file == ''
      name: Error - no kubeconfig provided
      shell: bash
      run: |
        echo "Error: You must provide either `kubeconfig` or `kubeconfig-file`"
        exit 1
    - if: inputs.kubeconfig != '' && inputs.kubeconfig-file != ''
      name: Error - both kubeconfig and kubeconfig-file provided
      shell: bash
      run: |
        echo "Error: You must provide either `kubeconfig` or `kubeconfig-file` but not both"
        exit 1
    - env:
        DESIRED_VERSION: ${{ inputs.helm-version }}
      name: Install Helm ${{ inputs.helm-version }}
      run: curl -fsSL https://git.io/get_helm.sh | bash
      shell: bash
    - if: inputs.update-dependencies == '1'
      name: Update Helm dependencies
      run: helm dep update ${{ inputs.chart-dir }} --skip-refresh
      shell: bash
    - if: inputs.build-dependencies == '1'
      name: Build Helm dependencies
      run: helm dep build ${{ inputs.chart-dir }} --skip-refresh
      shell: bash
    - if: inputs.values-file != ''
      name: Prepare values file
      run: |
        cat << 'EOF' > ${{ github.run_id }}
        ${{ inputs.values-file }}
        EOF
        chmod 600 ${{ github.run_id }}
      shell: bash
    - name: Prepare KUBECONFIG
      if: inputs.kubeconfig != '' && inputs.kubeconfig-file != ''
      run: |
        cat << 'EOF' > /tmp/kubeconfig
        ${{ inputs.kubeconfig }}
        EOF
        chmod 600 /tmp/kubeconfig
      shell: bash
    - name: Deploy with Helm
      run: |
        helm ${{ inputs.action }} ${{ inputs.release-name }} ${{ inputs.chart-dir }} \
          --kubeconfig ${{ inputs.kubeconfig-file || '/tmp/kubeconfig' }} \
          --namespace ${{ inputs.namespace }} \
          $([[ "${{ inputs.create-namespace }}" == "1" ]] && echo '--create-namespace') \
          $([[ "${{ inputs.atomic }}" == "1" ]] && echo '--atomic') \
          $([[ "${{ inputs.wait }}" == "1" ]] && echo '--wait') \
          $([[ "${{ inputs.values-file }}" != "" ]] && echo "--values ${{ github.run_id }}") \
          $([[ "${{ inputs.values-filepath }}" != "" ]] && echo "--values ${{ inputs.values-filepath }}") \
          $([[ "${{ inputs.values }}" != "" ]] && echo "--set ${{ inputs.values }}")
      shell: bash
